spring:
  data:
    mongodb:
      host: 15.164.151.130
      port: 27017
      database: lottoManager
      username: chatbot
      password: cotqht123!
      authentication-database: admin
  #      uri: mongodb://chatbot:cotqht123!@15.164.151.130:27017/chatbot3?authSource=admin
  application:
    name: ttokey-lottomanager-service

